### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by itzVort3x1** [itzVort3x1/shell-cpp#1]
Refactor the code to make it more modular and divide it into multiple files.

**Comment by AB1775** [comment]
Hi @itzVort3x1, do you mind if I work on this? I'm thinking we could divide the functions into several categories, each category having its own header file:

**File Handling** - contains searchFileInDirectory(), printFileContents(), and isExecutable()
**Built-Ins** - contains the declaration for the predefined shell built-in commands and searchBuiltIn()
**String Manipulation** - contains split_string(), parseArgument, and parseFileNames()

From here, we could include each header file in an "include" directory and modify the g++ command from your README:
```bash
g++ -std=c++17 -I../include -o main main.cpp
```

**Comment by itzVort3x1** [comment]
@AB1775 Hey, Sure sounds good. I have sent you an invite for collaborator!
